apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels: # these are replicaset labels
    # purpose: dp-demo
    purpose: headless-svc-demo
    project: roboshop
spec:
  replicas: 4
  selector: # this labels are used to select pods
    matchLabels:
      purpose: headless-svc-demo
      project: roboshop
  # pod defination    
  template:
    metadata:
      labels:
        purpose: headless-svc-demo
        project: roboshop
    spec:
      containers:
      - name: nginx
       # image: nginx:trixie-perl
        image: nginx:latest

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: headless-svc-demo
    project: roboshop
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port     

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
spec:
# if a service has a cluster ip none, then it is called as headless service
  clusterIP: None
  selector:
    purpose: headless-svc-demo
    project: roboshop
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port         